### ISSUE TITLE
初始不显示的问题

### ISSUE THREAD

**Issue by artiely** [vxhly/vuepress-plugin-one-click-copy#1]
第一次进入页面没有显示，再次刷新就好了，不知作者是否知道是什么原因。

**Comment by vxhly** [comment]
可能是没有加载出来哦发自我的iPhone------------------ 原始邮件 ------------------发件人: artiely  <notifications@github.com>发送时间: 2020年3月29日 18:00收件人: vxhly/vuepress-plugin-one-click-copy <vuepress-plugin-one-click-copy@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[vxhly/vuepress-plugin-one-click-copy] 初始不显示的问题 (#1)
第一次进入页面没有显示，再次刷新就好了，不知作者是否知道是什么原因。

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/vxhly/vuepress-plugin-one-click-copy/issues/1",
"url": "https://github.com/vxhly/vuepress-plugin-one-click-copy/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
